server:
  port: 20001
spring:
  application:
    name: shirodemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?serverTimezone=GMT%2B8
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    mode: html5
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  type-aliases-package: com.yyzc.hy.shiro.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
